### ISSUE TITLE
[Question] このパッケージをPyPIにあげる予定はありますか？

### ISSUE THREAD

**Issue by yocjyet** [iigura/egGTFS#1]
[再履バス同好会](https://github.com/sairidoukoukai)の于です。当会では、OuDiaとGTFS-JPの相互変換用Pythonライブラリを制作し、PyPIにてパッケージとして公開する予定です。その際に車輪を再発明しないため、貴ライブラリに依存したい次第ですが、もしPyPIにて公開していただければ大変ありがたいのですが、その予定はありますでしょうか？

**Comment by iigura** [comment]
はい。PyPI にて公開したく思っています。
公開にむけて作業を開始しますので、少しお時間下さい。
よろしくお願いいたします。

**Comment by yocjyet** [comment]
早速ありがとうございます！よろしくお願い致します。

**Comment by iigura** [comment]
パッケージリリース用のテストサーバーである TestPyPI でのテストは終わりました。
PyPI での正式リリースのための各種の作業は明日以降に行いますので、もう少々お待ち下さい。

**Comment by iigura** [comment]
PyPI への登録完了しました。
    pip install egGTFS
にてインストールできると思います。
お試し下さい。

issue をチェックするために、今回、普段確認しているメールアドレスも git に登録しました。
ただ、アカウント設定等の作業が苦手なので、上手くできているか自信がありません。

もし、issue を書いても、しばらく反応がなかった場合は入門ガイド（PDF）のあとがきにある連絡先アドレスまで連絡いただければ幸いです。

**Comment by yocjyet** [comment]
早速の丁寧なご対応、どうもありがとうございました！先ほど無事動作確認できました。お陰様で変換ライブラリの開発が捗りそうです。（一応[リポジトリ](https://github.com/sairidoukoukai/oudia/)を公開しております。）

将来的には需要に応じてIssueやPull Requestなどを行っていくつもりです。よろしくお願いいたします。
